import type { ExpenseCategory, Leg, Payer, ScheduleItem, ScheduleKind, Stop, SuggestedStop } from "./types.ts";

// Date fisse dei voli intercontinentali: arrivo a Pechino e partenza da Shanghai.
export const ARRIVAL_KEY = "2026-11-17";
export const DEPARTURE_KEY = "2026-12-04";
export const TRIP_NIGHTS = 17;
export const FLIGHTS_COST = 1384.44;
export const PLAN_VERSION = 6;
/** Prima e ultima tappa coincidono con i voli: non si spostano e non si eliminano. */
export const LOCKED_STOP_IDS = ["beijing", "shanghai"];
export const DEFAULT_CNY_PER_EURO = 8;

export const BUILT_IN_CATEGORIES = [
  { value: "visita", label: "Visita" },
  { value: "cibo", label: "Cibo" },
  { value: "tempo-libero", label: "Tempo libero" },
  { value: "shopping", label: "Shopping" },
  { value: "spettacolo", label: "Spettacolo" },
];
export const KIND_LABELS: Record<ScheduleKind, string> = {
  activity: "Attività",
  transport: "Trasporto",
  hotel: "Hotel / notte",
};
export const ALLOWED_EMAILS = new Set([
  "bebroggi@gmail.com",
  "sofiakovaleva1998@gmail.com",
]);
export const PAYER_LABELS: Record<Payer, string> = { alberto: "Alberto", sofia: "Sofia" };
export const EXPENSE_CATEGORIES: Array<{ value: ExpenseCategory; label: string }> = [
  { value: "hotel", label: "Hotel" },
  { value: "trasporti", label: "Trasporti" },
  { value: "attivita", label: "Attività" },
  { value: "cibo", label: "Cibo" },
  { value: "voli", label: "Voli" },
  { value: "extra", label: "Extra" },
];
export const DEFAULT_COST_ENTRIES = [
  { id: "food", label: "Cibo e bevande", amount: 900, currency: "EUR" as const },
  { id: "local", label: "Trasporti locali", amount: 300, currency: "EUR" as const },
  { id: "extras", label: "Assicurazione, connettività ed extra", amount: 720, currency: "EUR" as const },
];

export const initialStops: Stop[] = [
  {
    id: "beijing",
    name: "Pechino",
    lat: 39.9042,
    lng: 116.4074,
    nights: 3,
    hotelNightly: 95,
    activities: [
      { id: "forbidden-city", name: "Città Proibita + Jingshan", description: "Prenotazione online obbligatoria con passaporto, 7 gg prima; chiuso lunedì", price: 12, selected: false },
      { id: "great-wall", name: "Grande Muraglia di Mutianyu", description: "40 ¥ ingresso + 15 ¥ navetta + 140 ¥ funivia A/R a testa; poca folla a novembre", price: 49, selected: false },
      { id: "temple-heaven", name: "Tempio del Cielo", description: "Cumulativo 28 ¥/pp in bassa stagione; al mattino tai chi e vita locale", price: 7, selected: false },
      { id: "summer-palace", name: "Palazzo d'Estate", description: "Biglietto completo 50 ¥/pp (nov–mar); lago Kunming, possibile ghiaccio", price: 13, selected: false },
      { id: "peking-duck", name: "Anatra alla pechinese (Siji Minfu)", description: "Anatra intera ~259 ¥ + contorni; prenotare o coda presto, file lunghe", price: 50, selected: false },
      { id: "hutong-houhai", name: "Hutong e lago Houhai", description: "Gratis; passeggiata nei vicoli storici e tramonto sul lago", price: 0, selected: false },
      { id: "lama-temple", name: "Tempio dei Lama (Yonghegong)", description: "25 ¥/pp con incenso incluso; chiude alle 16 in inverno", price: 6, selected: false },
    ],
  },
  {
    id: "xian",
    name: "Xi’an",
    lat: 34.3416,
    lng: 108.9398,
    nights: 2,
    hotelNightly: 85,
    activities: [
      { id: "terracotta", name: "Esercito di Terracotta", description: "120 ¥/pp, biglietto nominativo con passaporto, max 7 gg prima; mezza giornata", price: 30, selected: false },
      { id: "city-wall-bike", name: "Mura della città in bicicletta", description: "54 ¥ ingresso + 45 ¥ bici per 3h; partenza Porta Sud, giro completo 14 km", price: 25, selected: false },
      { id: "muslim-quarter", name: "Quartiere musulmano e street food", description: "Gratis; serata tra bancarelle: roujiamo e biangbiang noodles", price: 0, selected: false },
      { id: "big-wild-goose-pagoda", name: "Grande Pagoda dell'Oca Selvatica", description: "Tempio ~40 ¥ + salita 25 ¥; la sera fontane danzanti gratuite", price: 16, selected: false },
      { id: "tang-dynasty-show", name: "Tang Dynasty Show con banchetto di ravioli", description: "~350 ¥/pp show + cena (solo show 218 ¥); ore 19:30, prenotare", price: 88, selected: false },
    ],
  },
  {
    id: "chengdu",
    name: "Chengdu",
    lat: 30.5728,
    lng: 104.0668,
    nights: 2,
    hotelNightly: 80,
    activities: [
      { id: "pandas", name: "Chengdu Panda Base", description: "55 ¥/pp, prenotare online; arrivare alle 7:30–9, i panda sono attivi al mattino", price: 14, selected: false },
      { id: "sichuan-opera", name: "Opera del Sichuan e cambio faccia", description: "~180–320 ¥/pp con tè (Shufeng Yayun); show ore 20, posti centrali in anticipo", price: 55, selected: false },
      { id: "peoples-park", name: "Casa da tè al Parco del Popolo", description: "Parco gratuito, tè 20–30 ¥; pulizia orecchie, mahjong e atmosfera locale", price: 6, selected: false },
      { id: "jinli-street", name: "Jinli Street e Tempio di Wuhou", description: "Via gratuita, magica di sera con le lanterne; tempio adiacente ~50 ¥ opz.", price: 0, selected: false },
      { id: "leshan-buddha", name: "Buddha Gigante di Leshan (day trip)", description: "Treno AV ~1h + ingresso 50 ¥ inverno; crociera 70 ¥ opz., giornata intera", price: 46, selected: false },
      { id: "wenshu-monastery", name: "Monastero di Wenshu", description: "Gratuito; monastero attivo con casa da tè storica e ristorante vegetariano", price: 0, selected: false },
    ],
  },
  {
    id: "kunming",
    name: "Kunming · Yunnan",
    lat: 25.0389,
    lng: 102.7183,
    nights: 3,
    hotelNightly: 75,
    activities: [
      { id: "stone-forest", name: "Foresta di Pietra di Shilin", description: "Karst UNESCO a 90 min; 130 ¥/pp + navetta 25 ¥, prenotare su Trip.com", price: 33, selected: false },
      { id: "green-lake-gulls", name: "Green Lake e gabbiani siberiani", description: "Gratis; da novembre migliaia di gabbiani dal Bajkal, meglio al mattino", price: 0, selected: false },
      { id: "western-hills-dragon-gate", name: "Colline Occidentali e Porta del Drago", description: "40 ¥/pp + navetta; vista sul lago Dianchi", price: 16, selected: false },
      { id: "dianchi-haigeng", name: "Diga di Haigeng sul lago Dianchi", description: "Gratis; gabbiani nov–mar e tramonto spettacolare, si abbina alle Colline", price: 0, selected: false },
      { id: "yuantong-temple", name: "Tempio Yuantong", description: "Tempio buddista di 1200 anni in centro; ingresso simbolico, 8–18", price: 2, selected: false },
      { id: "flower-bird-market", name: "Mercato dei fiori e degli uccelli", description: "Gratis; bazar storico vicino al Green Lake, ottimo in inverno", price: 0, selected: false },
    ],
  },
  {
    id: "zhangjiajie",
    name: "Zhangjiajie",
    lat: 29.347,
    lng: 110.4792,
    nights: 2,
    hotelNightly: 90,
    activities: [
      { id: "forest-park", name: "Parco Nazionale · Yuanjiajie/Avatar e Tianzi", description: "239 ¥/pp valido 4 giorni con bus interni; prenotazione online obbligatoria", price: 60, selected: false },
      { id: "tianmen-mountain", name: "Tianmen Mountain con funivia e skywalk", description: "258 ¥/pp con funivia (225 da dic); nebbia frequente, skywalk in vetro", price: 65, selected: false },
      { id: "grand-canyon-glass-bridge", name: "Glass Bridge del Grand Canyon", description: "178 ¥/pp canyon + ponte; prenotare slot orario, può chiudere per ghiaccio", price: 45, selected: false },
      { id: "bailong-elevator", name: "Ascensore Bailong", description: "65 ¥/pp a tratta; sale 326 m nella roccia verso Yuanjiajie, extra al pass", price: 16, selected: false },
      { id: "tianzi-cable-car", name: "Funivia di Tianzi Mountain", description: "~65 ¥/pp a tratta; risparmia la salita a piedi, picchi nella nebbia", price: 16, selected: false },
    ],
  },
  {
    id: "fenghuang",
    name: "Fenghuang",
    lat: 27.9483,
    lng: 109.5987,
    nights: 1,
    hotelNightly: 65,
    activities: [
      { id: "tuojiang", name: "Barca sul fiume Tuojiang", description: "80 ¥/pp di giorno, 120 ¥ di notte (~30 min); la notturna è la più scenica", price: 30, selected: false },
      { id: "old-town-night", name: "Città antica illuminata di notte", description: "Gratis; luci su palafitte, torre Wanming e Hong Bridge fino a tarda sera", price: 0, selected: false },
      { id: "combo-ticket-attractions", name: "Biglietto combinato 8 attrazioni", description: "128 ¥/pp per 2 giorni: casa di Shen Congwen, East Gate, museo", price: 32, selected: false },
      { id: "stepping-stones-bridges", name: "Pietre del guado e ponti sul Tuojiang", description: "Gratis; attraversata sulle pietre all'alba con la foschia, prima della folla", price: 0, selected: false },
    ],
  },
  {
    id: "wuzhen",
    name: "Wuzhen",
    lat: 30.7462,
    lng: 120.4943,
    nights: 1,
    hotelNightly: 100,
    activities: [
      { id: "xizha", name: "Xizha illuminata di sera", description: "150 ¥/pp; luci dal tramonto (~17 a dicembre); dormire nel borgo è il top", price: 38, selected: false },
      { id: "canal-night-boat", name: "Barca notturna sui canali", description: "Privata ~480 ¥ fino a 8 posti; condivisa 60 ¥/pp", price: 60, selected: false },
      { id: "dongzha-morning", name: "Dongzha al mattino", description: "110 ¥/pp; conviene il combinato Xizha+Dongzha a 190 ¥; case-museo", price: 28, selected: false },
      { id: "folk-shows", name: "Spettacoli folk inclusi", description: "Ombre cinesi, opera e tintoria di indaco inclusi nel biglietto; orari invernali", price: 0, selected: false },
    ],
  },
  {
    id: "suzhou",
    name: "Suzhou",
    lat: 31.2989,
    lng: 120.5853,
    nights: 1,
    hotelNightly: 75,
    activities: [
      { id: "humble-garden", name: "Giardino dell’Umile Amministratore", description: "70 ¥/pp bassa stagione; prenotare online con passaporto, chiude alle 17", price: 18, selected: false },
      { id: "pingjiang-road", name: "Pingjiang Road", description: "Gratis; canale storico, case da tè e negozi, perfetta nel tardo pomeriggio", price: 0, selected: false },
      { id: "suzhou-museum", name: "Museo di Suzhou (I.M. Pei)", description: "Gratuito; prenotazione WeChat 7 gg prima con passaporto; chiuso lunedì", price: 0, selected: false },
      { id: "master-of-nets-night", name: "Master of the Nets serale", description: "Show ~120 ¥/pp ma spesso sospeso d'inverno: verificare, altrimenti diurna", price: 30, selected: false },
      { id: "tiger-hill", name: "Tiger Hill e pagoda pendente", description: "60 ¥/pp a dicembre; simbolo di Suzhou, 2–3 ore con il parco", price: 15, selected: false },
      { id: "shantang-street", name: "Shantang Street di sera", description: "Gratis; lanterne rosse sui canali, sale interne a pagamento", price: 0, selected: false },
    ],
  },
  {
    id: "shanghai",
    name: "Shanghai",
    lat: 31.2304,
    lng: 121.4737,
    nights: 2,
    hotelNightly: 120,
    activities: [
      { id: "bund-night", name: "Bund illuminato di sera", description: "Gratis; skyline di Pudong acceso ~18:30–22; a dicembre vento freddo", price: 0, selected: false },
      { id: "tower", name: "Shanghai Tower Observatory", description: "180 ¥/pp per il 118° piano; prenotare online, scegliere giornata limpida", price: 45, selected: false },
      { id: "yu-garden", name: "Yu Garden e bazaar", description: "~40 ¥/pp, chiuso lunedì; il bazaar attorno è gratuito e scenografico la sera", price: 10, selected: false },
      { id: "huangpu-cruise", name: "Crociera serale sull'Huangpu", description: "115 ¥/pp in bassa stagione, 50 min da Shiliupu; prenotare su Trip.com", price: 29, selected: false },
      { id: "french-concession", name: "Concessione Francese e Wukang Road", description: "Gratis; platani, ville e caffè tra Wukang Road e Tianzifang", price: 0, selected: false },
      { id: "shanghai-museum", name: "Museo di Shanghai", description: "Gratuito; prenotazione online con passaporto, chiuso lunedì; bronzi e giade", price: 0, selected: false },
    ],
  },
];

export const SUGGESTED_STOPS: SuggestedStop[] = [
  {
    // Tappa del piano originale: se l'avete tolta, torna con panda e attività già pronte.
    ...initialStops.find((stop) => stop.id === "chengdu")!,
    insertAfterId: "xian",
    recap: "Panda giganti al mattino, case da tè, opera del Sichuan con il cambio faccia e la cucina più piccante della Cina. Dal 2025 c'è anche l'AV diretta per Zhangjiajie (~4h) che passa da Chongqing.",
    transport: "AV da Xi'an Nord 3h30–4h; poi Chongqing 1h15–1h45 o Zhangjiajie Ovest diretto ~4h",
    season: "Fresco e grigio (8–14°C), poca pioggia; panda attivi nelle mattine fredde",
  },
  {
    id: "chongqing",
    name: "Chongqing",
    lat: 29.563,
    lng: 106.552,
    nights: 2,
    hotelNightly: 60,
    insertAfterId: "chengdu",
    recap: "La metropoli cyberpunk sul Yangtze: grattacieli a strapiombo, monorotaia tra i palazzi, hotpot leggendario e le sculture UNESCO di Dazu. Deviazione facilissima da Chengdu.",
    transport: "Treno AV da Chengdu Est 1h15–2h, ~154 ¥ (150 corse al giorno)",
    season: "Mite (10–15°C) ma capitale della nebbia; luci notturne comunque spettacolari, hotel scontati",
    activities: [
      { id: "hongya-cave", name: "Hongyadong illuminata di notte", description: "Palafitte di 11 piani, gratis; al tramonto, vista dal ponte Qiansimen", price: 0, selected: false },
      { id: "dazu-rock-carvings", name: "Sculture rupestri di Dazu (UNESCO)", description: "Mezza giornata a Baodingshan; biglietto invernale ridotto ~120 ¥/pp", price: 30, selected: false },
      { id: "yangtze-cableway", name: "Funivia sul fiume Yangtze", description: "Traversata panoramica, ~30 ¥ A/R a testa; meglio nei feriali", price: 8, selected: false },
    ],
  },
  {
    id: "guilin",
    name: "Guilin & Yangshuo",
    lat: 25.274,
    lng: 110.29,
    nights: 3,
    hotelNightly: 65,
    insertAfterId: "kunming",
    recap: "Il paesaggio carsico più iconico della Cina: crociera sul fiume Li tra i pinnacoli fino a Yangshuo, risaie e bambù. A dicembre pochissimi turisti e clima secco.",
    transport: "Volo da Chengdu ~2h (500–1100 ¥) o treno AV da Kunming ~4h30 (~250 ¥)",
    season: "Stagione secca: 13–21°C di giorno; fiume in magra (crociera a volte accorciata), foschia al mattino",
    activities: [
      { id: "li-river-cruise", name: "Crociera sul fiume Li fino a Yangshuo", description: "4–4,5h tra i pinnacoli; 3 stelle 215 ¥/pp, 4 stelle 360–480 ¥", price: 55, selected: false },
      { id: "yulong-bamboo-raft", name: "Zattera di bambù sul fiume Yulong", description: "Zattera per 2 ~220 ¥ tra risaie e ponti antichi", price: 28, selected: false },
      { id: "reed-flute-cave", name: "Grotta del Flauto di Canna", description: "Stalattiti illuminate in città, ~90 ¥/pp, visita 1h", price: 23, selected: false },
    ],
  },
  {
    id: "lijiang",
    name: "Lijiang",
    lat: 26.855,
    lng: 100.227,
    nights: 3,
    hotelNightly: 55,
    insertAfterId: "kunming",
    recap: "Città vecchia Naxi patrimonio UNESCO ai piedi della Montagna Innevata del Drago di Giada: a inizio dicembre cieli tersi e vicoli senza folla. La più romantica del gruppo.",
    transport: "Treno da Kunming 3–3,5h, 166–220 ¥ (12 coppie di treni al giorno)",
    season: "Sole quasi garantito: ~14°C di giorno ma fino a 0°C la notte; bassa stagione, prezzi ridotti",
    activities: [
      { id: "jade-dragon-snow-mountain", name: "Montagna Innevata del Drago di Giada", description: "Ingresso ~100 ¥ + funivia Glacier Park ~140 ¥/pp; prenotare la funivia", price: 60, selected: false },
      { id: "lijiang-old-town", name: "Città vecchia e Stagno del Drago Nero", description: "Vicoli e canali Naxi; tassa 50 ¥/pp che include il parco", price: 13, selected: false },
      { id: "shuhe-old-town", name: "Borgo antico di Shuhe in bici", description: "Versione tranquilla di Lijiang a 20 min, ingresso libero", price: 0, selected: false },
    ],
  },
  {
    id: "dali",
    name: "Dali",
    lat: 25.606,
    lng: 100.268,
    nights: 2,
    hotelNightly: 50,
    insertAfterId: "kunming",
    recap: "Atmosfera rilassata tra il lago Erhai e i monti Cangshan, cultura Bai e borghi come Xizhou: il ritmo lento ideale per spezzare l'itinerario.",
    transport: "Treno AV da Kunming ~2h, 109–155 ¥; da Dali a Lijiang altri ~2h di treno",
    season: "Il mese più secco: sole e ~16°C di giorno, 3°C la notte, vento sul lago; pochissimi turisti",
    activities: [
      { id: "three-pagodas", name: "Tre Pagode del Tempio Chongsheng", description: "Icona millenaria col riflesso nel laghetto; ~121 ¥/pp, 2–3h", price: 30, selected: false },
      { id: "erhai-lake-loop", name: "Giro del lago Erhai in e-bike", description: "Scooter elettrico 60–100 ¥ al giorno; tappe a Xizhou e Shuanglang", price: 12, selected: false },
      { id: "cangshan-cableway", name: "Funivia sui monti Cangshan", description: "Funivia Gantong ~80 ¥/pp e sentiero panoramico Jade Belt", price: 20, selected: false },
    ],
  },
  {
    id: "emeishan",
    name: "Emeishan",
    lat: 29.601,
    lng: 103.484,
    nights: 2,
    hotelNightly: 65,
    insertAfterId: "chengdu",
    recap: "Montagna sacra buddhista con la statua dorata a 3.079 m sopra il mare di nuvole: in inverno neve in vetta e terme ai piedi del monte. Si abbina al Buddha di Leshan, a un'ora da Chengdu.",
    transport: "Treno AV da Chengdu 1h–1h30 (~55–65 ¥); navetta interna 90 ¥ A/R",
    season: "Neve da metà dicembre in quota; stagione Ice & Snow con terme, ingresso ridotto 110 ¥",
    activities: [
      { id: "cima-dorata-jinding", name: "Cima Dorata (Jinding)", description: "Ingresso 110–160 ¥ + bus 90 ¥ + funivia ~50 ¥; alba sul mare di nuvole", price: 60, selected: false },
      { id: "buddha-gigante-leshan", name: "Buddha Gigante di Leshan", description: "Statua rupestre di 71 m, mezza giornata in treno da Emeishan; 80 ¥", price: 20, selected: false },
      { id: "terme-di-emei", name: "Terme ai piedi del monte", description: "Sorgenti calde serali (es. Lingxiu Hot Spring), 150–200 ¥/pp", price: 45, selected: false },
    ],
  },
  {
    id: "xiamen",
    name: "Xiamen",
    lat: 24.48,
    lng: 118.089,
    nights: 2,
    hotelNightly: 70,
    insertAfterId: "fenghuang",
    recap: "L'unica tappa mite possibile a dicembre: città di mare rilassata con l'isola pedonale di Gulangyu (UNESCO), ville coloniali e caffè. Richiede però una deviazione lunga.",
    transport: "Volo da Changsha (vicino Fenghuang) 1h30 (~60–110 € a testa) o AV da Shanghai ~5h",
    season: "Mite e soleggiato (11–20°C), bassa stagione; il vento può sospendere i traghetti",
    activities: [
      { id: "gulangyu-sunlight-rock", name: "Gulangyu e Sunlight Rock", description: "Traghetto A/R 35 ¥ + rocca panoramica 50 ¥; ville coloniali", price: 21, selected: false },
      { id: "tempio-nanputuo", name: "Tempio Nanputuo", description: "Tempio buddhista accanto all'università; gratuito", price: 0, selected: false },
      { id: "zengcuoan-lungomare", name: "Zengcuoan e lungomare", description: "Ex villaggio di pescatori con street food e caffè; gratis", price: 0, selected: false },
    ],
  },
  {
    id: "hangzhou",
    name: "Hangzhou",
    lat: 30.274,
    lng: 120.155,
    nights: 2,
    hotelNightly: 75,
    insertAfterId: "wuzhen",
    recap: "Il Lago dell'Ovest è il paesaggio classico della poesia cinese: pagode, ponti e colline di tè a 45 minuti da Shanghai. Si incastra tra Wuzhen e Suzhou senza stravolgere l'itinerario.",
    transport: "Bus diretto da Wuzhen ~1h; AV per Suzhou ~1h30 o Shanghai 45–60 min (~73 ¥)",
    season: "Freddo secco (0–10°C), poca pioggia, folla minima; hotel a prezzi invernali",
    activities: [
      { id: "crociera-lago-ovest", name: "Crociera sul Lago dell'Ovest", description: "Battello per le Tre Pagode riflesse; al tramonto, 55–70 ¥/pp", price: 18, selected: false },
      { id: "lingyin-feilai-feng", name: "Tempio Lingyin e Feilai Feng", description: "Area gratuita da dic 2025 (prenotare su WeChat); tempio 30 ¥", price: 8, selected: false },
      { id: "villaggio-te-longjing", name: "Villaggio del tè Longjing", description: "Colline di tè Dragon Well, ingresso libero; degustazione ~50 ¥/pp", price: 13, selected: false },
    ],
  },
  {
    id: "huangshan",
    name: "Huangshan e borghi Hui",
    lat: 29.717,
    lng: 118.339,
    nights: 2,
    hotelNightly: 95,
    insertAfterId: "wuzhen",
    recap: "Le Montagne Gialle innevate con pini brinati e mare di nuvole sono lo scenario più iconico della Cina; in inverno folla ai minimi. Con i borghi UNESCO Hongcun e Xidi.",
    transport: "Treno AV da Hangzhou 1h15 (~112 ¥) o da Shanghai ~3h; poi bus ~1h per Tangkou",
    season: "Tariffa invernale (150 ¥ invece di 230); neve e ghiaccio probabili, ramponi utili, notte in vetta per l'alba",
    activities: [
      { id: "vetta-huangshan", name: "Scalata dello Huangshan", description: "Ingresso inverno 150 ¥ + funivia Yungu 65 ¥ a tratta; notte in vetta", price: 70, selected: false },
      { id: "borgo-hongcun", name: "Borgo di Hongcun", description: "Villaggio UNESCO del film La tigre e il dragone; 104 ¥, valido 3 giorni", price: 26, selected: false },
      { id: "borgo-xidi", name: "Borgo di Xidi", description: "Architettura Hui e vicoli lastricati, più quieto di Hongcun; 104 ¥/pp", price: 26, selected: false },
    ],
  },
  {
    id: "pingyao",
    name: "Pingyao",
    lat: 37.2,
    lng: 112.176,
    nights: 1,
    hotelNightly: 45,
    insertAfterId: "beijing",
    recap: "La città murata Ming meglio conservata della Cina (UNESCO): mura intatte, le prime banche dell'800, cortili e lanterne rosse. Spezza perfettamente il viaggio Pechino → Xi'an ed è magica la sera.",
    transport: "Treno AV da Pechino ~4h (staz. Pingyao Gucheng), poi AV per Xi'an ~3h: tappa a metà strada",
    season: "Freddo secco (−5/5°C) ma cieli tersi e vicoli quasi vuoti; guesthouse nei cortili storici a prezzi minimi",
    activities: [
      { id: "pingyao-pass", name: "Biglietto unico della città antica", description: "Mura, Rishengchang (prima banca cinese) e residenze; ~125 ¥/pp, valido 3 giorni", price: 32, selected: false },
      { id: "pingyao-qiao", name: "Cortile della famiglia Qiao", description: "La residenza di «Lanterne rosse», a 40 min di auto; ~115 ¥/pp", price: 29, selected: false },
      { id: "pingyao-shuanglin", name: "Tempio Shuanglin", description: "Sculture in argilla dipinta uniche, a 6 km dalle mura; ~35 ¥/pp", price: 9, selected: false },
    ],
  },
  {
    id: "huashan",
    name: "Monte Hua (Huashan)",
    lat: 34.49,
    lng: 110.085,
    nights: 1,
    hotelNightly: 55,
    insertAfterId: "xian",
    recap: "La montagna sacra dell'ovest: creste di granito a strapiombo, scalinate scavate nella roccia e la famosa passerella di assi sospesa nel vuoto. Fattibile anche in giornata da Xi'an (idea dal blog Zipangu).",
    transport: "AV da Xi'an Nord a Huashan Nord in 30–40 min (~55 ¥); navetta + funivia fino in cresta",
    season: "In cresta freddo e vento (−5°C) ma cieli limpidi e sentieri deserti; ramponcini utili se ha nevicato",
    activities: [
      { id: "huashan-west-cable", name: "Funivia del Picco Ovest", description: "La salita più spettacolare; funivia ~140 ¥ + bus ~40 ¥ a tratta", price: 45, selected: false },
      { id: "huashan-plank-walk", name: "Passerella nel vuoto (Plank Walk)", description: "Assi di legno sul precipizio, imbrago incluso; ~30 ¥/pp", price: 8, selected: false },
      { id: "huashan-peaks-loop", name: "Anello dei cinque picchi", description: "Cresta tra picco Nord, Est e Sud; ingresso invernale ~100 ¥/pp", price: 25, selected: false },
    ],
  },
  {
    id: "luoyang",
    name: "Luoyang & Shaolin",
    lat: 34.62,
    lng: 112.454,
    nights: 2,
    hotelNightly: 50,
    insertAfterId: "xian",
    recap: "Le grotte di Longmen (UNESCO) con centomila Buddha scolpiti nella roccia e il monastero Shaolin sul monte Songshan, culla del kung fu: la grande deviazione storica a est di Xi'an suggerita dal blog.",
    transport: "AV da Xi'an Nord ~1h30 (~175 ¥); Shaolin a ~1h30 di bus/auto da Luoyang",
    season: "Freddo secco (0–8°C), siti all'aperto senza folla; spettacoli di kung fu al coperto",
    activities: [
      { id: "longmen-grottoes", name: "Grotte di Longmen", description: "100.000 statue rupestri sul fiume Yi, illuminate anche la sera; ~90 ¥/pp", price: 23, selected: false },
      { id: "shaolin-monastery", name: "Monastero Shaolin e foresta di pagode", description: "Spettacolo di kung fu incluso nel biglietto; ~80 ¥/pp + transfer", price: 20, selected: false },
      { id: "white-horse-temple", name: "Tempio del Cavallo Bianco", description: "Il primo tempio buddhista della Cina (68 d.C.); ~35 ¥/pp", price: 9, selected: false },
    ],
  },
  {
    id: "wudangshan",
    name: "Wudangshan",
    lat: 32.4,
    lng: 111.004,
    nights: 2,
    hotelNightly: 60,
    insertAfterId: "xian",
    recap: "La montagna del tai chi: monasteri taoisti UNESCO arroccati tra le nubi e la Vetta d'Oro. Il blog la segnala come nuova opzione: dal 30 giugno 2026 l'alta velocità Xi'an–Wuhan la mette a ~2h da Xi'an.",
    transport: "Nuova AV Xi'an → Wudangshan ~2h (linea aperta a giugno 2026); navetta interna al parco",
    season: "Freddo (0–10°C) e possibile neve sui gradini; con la nebbia l'atmosfera è ancora più mistica",
    activities: [
      { id: "wudang-golden-summit", name: "Vetta d'Oro (Jinding)", description: "Ingresso+bus ~230 ¥ + funivia ~90 ¥; tempio dorato a 1.612 m", price: 60, selected: false },
      { id: "wudang-zixiao", name: "Palazzo delle Nubi Purpuree", description: "Il complesso taoista meglio conservato, ~15 ¥ extra", price: 4, selected: false },
      { id: "wudang-taichi", name: "Lezione di tai chi", description: "1–2h con maestro locale nelle scuole ai piedi del monte; ~150 ¥/pp", price: 38, selected: false },
    ],
  },
  {
    id: "qingcheng-dujiangyan",
    name: "Qingchengshan & Dujiangyan",
    lat: 30.9,
    lng: 103.605,
    nights: 1,
    hotelNightly: 55,
    insertAfterId: "chengdu",
    recap: "Il monte taoista Qingcheng e l'antico sistema di irrigazione di Dujiangyan (entrambi UNESCO) a mezz'ora di treno da Chengdu: boschi sempreverdi, templi e ponti sospesi. Perfetta anche in giornata senza spostare i bagagli.",
    transport: "AV da Chengdu ~30–50 min (~15–25 ¥ a tratta); si può fare A/R in giornata",
    season: "Fresco e umido (5–12°C) ma il bosco resta verde; pochissimi visitatori",
    activities: [
      { id: "qingcheng-front", name: "Monte Qingcheng (versante anteriore)", description: "Templi taoisti nel bosco; ingresso ~80 ¥ + funivia ~35 ¥", price: 29, selected: false },
      { id: "dujiangyan-anlan", name: "Dujiangyan e ponte sospeso Anlan", description: "Capolavoro idraulico del 256 a.C. ancora in funzione; ~80 ¥/pp", price: 20, selected: false },
      { id: "dujiangyan-panda", name: "Base panda di Dujiangyan", description: "Molto più tranquilla di quella di Chengdu; ~55 ¥/pp", price: 14, selected: false },
    ],
  },
  {
    id: "putuoshan",
    name: "Putuoshan",
    lat: 30.007,
    lng: 122.387,
    nights: 2,
    hotelNightly: 75,
    insertAfterId: "suzhou",
    recap: "L'isola sacra di Guanyin nell'arcipelago di Zhoushan: templi in riva al mare, spiagge e la statua alta 33 m. È la montagna buddhista «sul mare» vicina a Shanghai citata dal blog.",
    transport: "AV Suzhou/Shanghai → Ningbo ~1h30, poi bus + traghetto (~2h); il vento forte può fermare i traghetti",
    season: "Clima costiero mite (5–12°C); nei feriali d'inverno pellegrini e turisti pochissimi",
    activities: [
      { id: "putuo-puji", name: "Tempio Puji e isola a piedi", description: "Ingresso isola ~140 ¥ + tempio ~5 ¥; sentieri costieri tra i templi", price: 37, selected: false },
      { id: "putuo-guanyin", name: "Statua di Nanhai Guanyin", description: "La Guanyin dorata di 33 m sul promontorio; ~6 ¥/pp", price: 2, selected: false },
      { id: "putuo-fanyin", name: "Grotta di Fanyin", description: "Tempio sospeso sulla scogliera dove «si sente la voce del mare»; ~5 ¥", price: 2, selected: false },
    ],
  },
  {
    id: "wuzhen",
    name: "Wuzhen",
    lat: 30.7462,
    lng: 120.4943,
    nights: 1,
    hotelNightly: 100,
    insertAfterId: "fenghuang",
    recap: "Il borgo d'acqua più scenografico della Cina: canali illuminati la sera, spettacoli folk e la magia di dormire dentro l'area scenica di Xizha. Se l'avete tolta dal piano, da qui la rimettete con un click.",
    transport: "Da Fenghuang treni via Changsha (7–9h, tratta delicata); da Hangzhou bus diretto ~1h",
    season: "Freddo umido (2–10°C) ma canali senza folla; luci accese dal tramonto (~17)",
    activities: [
      { id: "xizha", name: "Xizha illuminata di sera", description: "150 ¥/pp; luci dal tramonto (~17 a dicembre); dormire nel borgo è il top", price: 38, selected: false },
      { id: "canal-night-boat", name: "Barca notturna sui canali", description: "Privata ~480 ¥ fino a 8 posti; condivisa 60 ¥/pp", price: 60, selected: false },
      { id: "dongzha-morning", name: "Dongzha al mattino", description: "110 ¥/pp; conviene il combinato Xizha+Dongzha a 190 ¥; case-museo", price: 28, selected: false },
    ],
  },
  {
    id: "suzhou",
    name: "Suzhou",
    lat: 31.2989,
    lng: 120.5853,
    nights: 2,
    hotelNightly: 75,
    insertAfterId: "wuzhen",
    recap: "La «Venezia d'Oriente» dei giardini classici UNESCO, dei canali e di Pingjiang Road: il blog Zipangu consiglia almeno due giorni pieni. Attività e prezzi già pronti se volete rimetterla nel piano.",
    transport: "AV per Shanghai in 25–40 min (~20 €); da Wuzhen ~1h30 di Didi o bus, da Hangzhou AV ~1h30",
    season: "Freddo secco (0–10°C), giardini quieti; alcuni show serali sospesi d'inverno",
    activities: [
      { id: "humble-garden", name: "Giardino dell’Umile Amministratore", description: "70 ¥/pp bassa stagione; prenotare online con passaporto, chiude alle 17", price: 18, selected: false },
      { id: "pingjiang-road", name: "Pingjiang Road", description: "Gratis; canale storico, case da tè e negozi, perfetta nel tardo pomeriggio", price: 0, selected: false },
      { id: "suzhou-museum", name: "Museo di Suzhou (I.M. Pei)", description: "Gratuito; prenotazione WeChat 7 gg prima con passaporto; chiuso lunedì", price: 0, selected: false },
      { id: "tiger-hill", name: "Tiger Hill e pagoda pendente", description: "60 ¥/pp a dicembre; simbolo di Suzhou, 2–3 ore con il parco", price: 15, selected: false },
    ],
  },
];

// Nomi in cinese di città e attività: servono per chiedere indicazioni o mostrarli a un tassista.
export const STOP_ZH: Record<string, string> = {
  beijing: "北京",
  xian: "西安",
  chengdu: "成都",
  kunming: "昆明",
  zhangjiajie: "张家界",
  fenghuang: "凤凰古城",
  wuzhen: "乌镇",
  suzhou: "苏州",
  shanghai: "上海",
  chongqing: "重庆",
  guilin: "桂林·阳朔",
  lijiang: "丽江",
  dali: "大理",
  emeishan: "峨眉山",
  xiamen: "厦门",
  hangzhou: "杭州",
  huangshan: "黄山",
  pingyao: "平遥古城",
  huashan: "华山",
  luoyang: "洛阳",
  wudangshan: "武当山",
  "qingcheng-dujiangyan": "青城山·都江堰",
  putuoshan: "普陀山",
};

export const ACTIVITY_ZH: Record<string, string> = {
  "forbidden-city": "故宫博物院",
  "great-wall": "慕田峪长城",
  "temple-heaven": "天坛公园",
  "summer-palace": "颐和园",
  "peking-duck": "四季民福烤鸭店",
  "hutong-houhai": "什刹海·后海",
  "lama-temple": "雍和宫",
  terracotta: "秦始皇兵马俑博物馆",
  "city-wall-bike": "西安城墙（南门）",
  "muslim-quarter": "回民街",
  "big-wild-goose-pagoda": "大雁塔",
  "tang-dynasty-show": "唐乐宫",
  pandas: "成都大熊猫繁育研究基地",
  "sichuan-opera": "蜀风雅韵（川剧变脸）",
  "peoples-park": "人民公园·鹤鸣茶社",
  "jinli-street": "锦里·武侯祠",
  "leshan-buddha": "乐山大佛",
  "wenshu-monastery": "文殊院",
  "stone-forest": "石林风景区",
  "green-lake-gulls": "翠湖公园",
  "western-hills-dragon-gate": "西山龙门",
  "dianchi-haigeng": "海埂大坝",
  "yuantong-temple": "圆通寺",
  "flower-bird-market": "景星花鸟市场",
  "forest-park": "张家界国家森林公园",
  "tianmen-mountain": "天门山",
  "grand-canyon-glass-bridge": "张家界大峡谷玻璃桥",
  "bailong-elevator": "百龙天梯",
  "tianzi-cable-car": "天子山索道",
  tuojiang: "沱江泛舟",
  "old-town-night": "凤凰古城",
  "combo-ticket-attractions": "凤凰古城景点联票",
  "stepping-stones-bridges": "沱江跳岩",
  xizha: "西栅景区",
  "canal-night-boat": "乌镇摇橹船",
  "dongzha-morning": "东栅景区",
  "folk-shows": "乌镇民俗表演",
  "humble-garden": "拙政园",
  "pingjiang-road": "平江路",
  "suzhou-museum": "苏州博物馆",
  "master-of-nets-night": "网师园",
  "tiger-hill": "虎丘",
  "shantang-street": "山塘街",
  "bund-night": "外滩",
  tower: "上海中心大厦",
  "yu-garden": "豫园",
  "huangpu-cruise": "黄浦江游船",
  "french-concession": "武康路·法租界",
  "shanghai-museum": "上海博物馆",
  "hongya-cave": "洪崖洞",
  "dazu-rock-carvings": "大足石刻",
  "yangtze-cableway": "长江索道",
  "li-river-cruise": "漓江游船",
  "yulong-bamboo-raft": "遇龙河竹筏",
  "reed-flute-cave": "芦笛岩",
  "jade-dragon-snow-mountain": "玉龙雪山",
  "lijiang-old-town": "丽江古城·黑龙潭",
  "shuhe-old-town": "束河古镇",
  "three-pagodas": "崇圣寺三塔",
  "erhai-lake-loop": "洱海",
  "cangshan-cableway": "苍山索道",
  "cima-dorata-jinding": "峨眉山金顶",
  "buddha-gigante-leshan": "乐山大佛",
  "terme-di-emei": "峨眉山温泉",
  "gulangyu-sunlight-rock": "鼓浪屿·日光岩",
  "tempio-nanputuo": "南普陀寺",
  "zengcuoan-lungomare": "曾厝垵",
  "crociera-lago-ovest": "西湖游船",
  "lingyin-feilai-feng": "灵隐寺·飞来峰",
  "villaggio-te-longjing": "龙井村",
  "vetta-huangshan": "黄山",
  "borgo-hongcun": "宏村",
  "borgo-xidi": "西递",
  "pingyao-pass": "平遥古城通票",
  "pingyao-qiao": "乔家大院",
  "pingyao-shuanglin": "双林寺",
  "huashan-west-cable": "华山西峰索道",
  "huashan-plank-walk": "长空栈道",
  "huashan-peaks-loop": "华山五峰",
  "longmen-grottoes": "龙门石窟",
  "shaolin-monastery": "少林寺",
  "white-horse-temple": "白马寺",
  "wudang-golden-summit": "武当山金顶",
  "wudang-zixiao": "紫霄宫",
  "wudang-taichi": "武当太极",
  "qingcheng-front": "青城山前山",
  "dujiangyan-anlan": "都江堰·安澜索桥",
  "dujiangyan-panda": "都江堰熊猫谷",
  "putuo-puji": "普济禅寺",
  "putuo-guanyin": "南海观音",
  "putuo-fanyin": "梵音洞",
};

export const initialLegs: Leg[] = [
  { id: "beijing-xian", fromId: "beijing", toId: "xian", mode: "🚄 Alta velocità", duration: "4h30–5h", cost: 120, included: true, note: "Beijing West → Xi’an North" },
  { id: "xian-chengdu", fromId: "xian", toId: "chengdu", mode: "🚄 Alta velocità", duration: "3h30–4h", cost: 95, included: true, note: "Xi’an North → Chengdu East" },
  { id: "chengdu-kunming", fromId: "chengdu", toId: "kunming", mode: "✈️ Volo diretto", duration: "1h30", cost: 150, included: true, note: "Protegge mezza giornata" },
  { id: "kunming-zhangjiajie", fromId: "kunming", toId: "zhangjiajie", mode: "🚄 Treno con cambio", duration: "5–11h30", cost: 110, included: true, note: "Verificare Huaihua o Changsha" },
  { id: "zhangjiajie-fenghuang", fromId: "zhangjiajie", toId: "fenghuang", mode: "🚄 Treno + Didi", duration: "~2h", cost: 45, included: true, note: "Arrivo a Fenghuanggucheng" },
  { id: "fenghuang-wuzhen", fromId: "fenghuang", toId: "wuzhen", mode: "🚄 Treni via Changsha", duration: "7–9h", cost: 130, included: true, note: "La tratta più delicata" },
  { id: "wuzhen-suzhou", fromId: "wuzhen", toId: "suzhou", mode: "🚕 Didi / transfer", duration: "1h30–2h", cost: 55, included: true, note: "Alternativa: bus diretto" },
  { id: "suzhou-shanghai", fromId: "suzhou", toId: "shanghai", mode: "🚄 Alta velocità", duration: "25–40 min", cost: 20, included: true, note: "Preferire stazioni centrali" },
];

// Base di trasferimenti noti (costo per 2, sempre modificabile): usata quando due tappe diventano
// consecutive e non c'è ancora una tratta salvata, al posto del generico "Trasporto da definire".
export const KNOWN_LEG_PRESETS: Record<string, { mode: string; duration: string; cost: number; note: string }> = {
  "beijing-wuzhen": { mode: "🚄 AV + taxi", duration: "5h30–6h", cost: 150, note: "Pechino Sud → Tongxiang in AV, poi ~20 min di taxi per Wuzhen" },
  "beijing-suzhou": { mode: "🚄 Alta velocità", duration: "4h–4h30", cost: 140, note: "Pechino Sud → Suzhou / Suzhou Nord" },
  "beijing-shanghai": { mode: "🚄 Alta velocità", duration: "4h30", cost: 150, note: "Pechino Sud → Shanghai Hongqiao" },
  "beijing-hangzhou": { mode: "🚄 Alta velocità", duration: "4h30–5h", cost: 155, note: "Pechino Sud → Hangzhou Est" },
  "beijing-pingyao": { mode: "🚄 Alta velocità", duration: "~4h", cost: 100, note: "Pechino → Pingyao Gucheng" },
  "pingyao-xian": { mode: "🚄 Alta velocità", duration: "~3h", cost: 80, note: "Pingyao Gucheng → Xi'an Nord" },
  "xian-huashan": { mode: "🚄 Alta velocità", duration: "30–40 min", cost: 30, note: "Xi'an Nord → Huashan Nord" },
  "xian-luoyang": { mode: "🚄 Alta velocità", duration: "~1h30", cost: 50, note: "Xi'an Nord → Luoyang Longmen" },
  "xian-wudangshan": { mode: "🚄 Alta velocità", duration: "~2h", cost: 60, note: "Nuova linea AV Xi'an–Wuhan (aperta a giugno 2026)" },
  "xian-chengdu": { mode: "🚄 Alta velocità", duration: "3h30–4h", cost: 95, note: "Xi’an North → Chengdu East" },
  "xian-zhangjiajie": { mode: "✈️ Volo diretto", duration: "1h50", cost: 150, note: "Xianyang → Hehua, ~19 voli a settimana (China Eastern, Sichuan Airlines…); niente AV diretta" },
  "chengdu-chongqing": { mode: "🚄 Alta velocità", duration: "1h15–1h45", cost: 40, note: "Chengdu East → Chongqing; ~160 ¥ a testa, corse ogni pochi minuti" },
  "chengdu-zhangjiajie": { mode: "🚄 Alta velocità", duration: "~4h", cost: 105, note: "Chengdu East → Zhangjiajie West diretto, es. G2445 08:00 → 11:58 (~415 ¥ a testa)" },
  "chongqing-zhangjiajie": { mode: "🚄 Alta velocità", duration: "2h49", cost: 62, note: "Chongqing East → Zhangjiajie West, es. G4601 09:24 → 12:13 (~246 ¥ a testa); ferma a Wulong Sud" },
  "zhangjiajie-shanghai": { mode: "✈️ Volo diretto", duration: "~2h", cost: 180, note: "Hehua → Pudong, 3 voli al giorno (mattina, pomeriggio, sera); in alternativa AV diretta G221 per Hongqiao ~7h20" },
  "chengdu-qingcheng-dujiangyan": { mode: "🚄 Alta velocità", duration: "30–50 min", cost: 15, note: "Chengdu → Qingchengshan / Dujiangyan, anche A/R in giornata" },
  "wuzhen-hangzhou": { mode: "🚌 Bus diretto", duration: "~1h", cost: 20, note: "Wuzhen → Hangzhou, bus frequenti" },
  "wuzhen-shanghai": { mode: "🚌 Bus / Didi", duration: "1h30–2h", cost: 60, note: "Wuzhen → Shanghai; in alternativa taxi per Tongxiang + AV" },
  "hangzhou-suzhou": { mode: "🚄 Alta velocità", duration: "~1h30", cost: 45, note: "Hangzhou Est → Suzhou" },
  "suzhou-putuoshan": { mode: "🚄 AV + bus + traghetto", duration: "~4h", cost: 90, note: "Suzhou → Ningbo in AV, poi bus e traghetto per Putuoshan" },
};

// Agenda iniziale con le date del piano originale: al caricamento ogni blocco riceve il suo
// giorno dentro la tappa ("day"), e da lì in poi la data si ricalcola dalle notti.
export const initialSchedule: ScheduleItem[] = [
  { id: "d01-arrival", date: "2026-11-17", stopId: "beijing", startTime: "12:25", endTime: "15:30", name: "Arrivo a Pechino e transfer", category: "trasporto", location: "PEK → hotel", notes: "Ritiro bagagli e check-in. Non fissare attività impegnative.", price: 0, bookingStatus: "prenotato" },
  { id: "d01-evening", date: "2026-11-17", stopId: "beijing", startTime: "17:30", endTime: "20:00", name: "Passeggiata nei hutong e cena", category: "cibo", location: "Shichahai / Gulou", notes: "Serata leggera per assorbire il fuso orario.", price: 35, bookingStatus: "non-serve" },
  { id: "d02-forbidden", date: "2026-11-18", stopId: "beijing", startTime: "08:30", endTime: "13:00", name: "Tian’anmen e Città Proibita", category: "visita", location: "Ingresso Meridian Gate", notes: "Passaporti con sé. Prenotare appena apre la finestra ufficiale.", price: 24, bookingStatus: "da-prenotare", sourceActivityId: "forbidden-city" },
  { id: "d02-jingshan", date: "2026-11-18", stopId: "beijing", startTime: "14:00", endTime: "17:00", name: "Jingshan e Beihai", category: "visita", location: "Jingshan Park", notes: "Salita al belvedere prima del tramonto.", price: 5, bookingStatus: "non-serve" },
  { id: "d03-wall", date: "2026-11-19", stopId: "beijing", startTime: "07:30", endTime: "16:30", name: "Grande Muraglia di Mutianyu", category: "visita", location: "Mutianyu", notes: "Partenza presto; verificare transfer privato o bus turistico.", price: 110, bookingStatus: "da-prenotare", sourceActivityId: "great-wall" },
  { id: "d03-duck", date: "2026-11-19", stopId: "beijing", startTime: "19:00", endTime: "21:00", name: "Cena con anatra alla pechinese", category: "cibo", location: "Dongcheng", notes: "Prenotare un ristorante vicino all’hotel.", price: 55, bookingStatus: "da-prenotare" },
  { id: "d04-train", date: "2026-11-20", stopId: "xian", startTime: "08:00", endTime: "14:30", name: "Treno Pechino → Xi’an", category: "trasporto", location: "Beijing West → Xi’an North", notes: "Arrivare in stazione almeno 60 minuti prima.", price: 0, bookingStatus: "da-prenotare" },
  { id: "d04-quarter", date: "2026-11-20", stopId: "xian", startTime: "17:30", endTime: "20:30", name: "Quartiere musulmano e Drum Tower", category: "cibo", location: "Huimin Jie", notes: "Street food e prima passeggiata sulle mura.", price: 30, bookingStatus: "non-serve" },
  { id: "d05-terracotta", date: "2026-11-21", stopId: "xian", startTime: "08:00", endTime: "14:00", name: "Esercito di Terracotta", category: "visita", location: "Emperor Qinshihuang’s Mausoleum", notes: "Transfer A/R; guida opzionale.", price: 60, bookingStatus: "da-prenotare", sourceActivityId: "terracotta" },
  { id: "d05-wall", date: "2026-11-21", stopId: "xian", startTime: "16:00", endTime: "19:00", name: "Mura di Xi’an al tramonto", category: "visita", location: "South Gate", notes: "Valutare noleggio bici in base al meteo.", price: 18, bookingStatus: "non-serve" },
  { id: "d06-train", date: "2026-11-22", stopId: "chengdu", startTime: "09:00", endTime: "14:30", name: "Treno Xi’an → Chengdu", category: "trasporto", location: "Xi’an North → Chengdu East", notes: "Check-in hotel e pomeriggio tranquillo.", price: 0, bookingStatus: "da-prenotare" },
  { id: "d06-jinli", date: "2026-11-22", stopId: "chengdu", startTime: "17:00", endTime: "20:30", name: "Jinli Street e cena Sichuan", category: "cibo", location: "Jinli Ancient Street", notes: "Chiedere livello di piccantezza medio.", price: 40, bookingStatus: "non-serve" },
  { id: "d07-pandas", date: "2026-11-23", stopId: "chengdu", startTime: "07:00", endTime: "12:30", name: "Chengdu Panda Base", category: "visita", location: "Research Base of Giant Panda Breeding", notes: "Essere all’ingresso all’apertura: i panda sono più attivi al mattino.", price: 30, bookingStatus: "da-prenotare", sourceActivityId: "pandas" },
  { id: "d07-tea", date: "2026-11-23", stopId: "chengdu", startTime: "15:00", endTime: "18:00", name: "People’s Park e casa da tè", category: "tempo-libero", location: "Heming Teahouse", notes: "Pomeriggio lento; eventuale opera Sichuan la sera.", price: 20, bookingStatus: "non-serve" },
  { id: "d08-flight", date: "2026-11-24", stopId: "kunming", startTime: "09:00", endTime: "13:00", name: "Volo Chengdu → Kunming", category: "trasporto", location: "CTU/TFU → KMG", notes: "Controllare aeroporto di partenza prima di prenotare.", price: 0, bookingStatus: "da-prenotare" },
  { id: "d08-lake", date: "2026-11-24", stopId: "kunming", startTime: "16:00", endTime: "19:00", name: "Green Lake e Yuantong Street", category: "tempo-libero", location: "Cuihu Park", notes: "Passeggiata di orientamento e cena Yunnan.", price: 25, bookingStatus: "non-serve" },
  { id: "d09-stone", date: "2026-11-25", stopId: "kunming", startTime: "08:00", endTime: "17:00", name: "Foresta di Pietra di Shilin", category: "visita", location: "Shilin Scenic Area", notes: "Escursione intera giornata; portare strato antivento.", price: 80, bookingStatus: "da-prenotare", sourceActivityId: "stone-forest" },
  { id: "d10-dianchi", date: "2026-11-26", stopId: "kunming", startTime: "09:30", endTime: "13:00", name: "Dianchi Lake e Western Hills", category: "visita", location: "Haigeng Park", notes: "Tenere il pomeriggio libero per lavanderia e preparazione treno.", price: 25, bookingStatus: "non-serve" },
  { id: "d10-buffer", date: "2026-11-26", stopId: "kunming", startTime: "15:00", endTime: "18:00", name: "Tempo cuscinetto e organizzazione", category: "tempo-libero", location: "Hotel / centro", notes: "Controllare biglietti e meteo per Zhangjiajie.", price: 0, bookingStatus: "non-serve" },
  { id: "d11-transfer", date: "2026-11-27", stopId: "zhangjiajie", startTime: "07:30", endTime: "16:30", name: "Kunming → Zhangjiajie", category: "trasporto", location: "Treno con cambio / volo", notes: "Tratta critica: bloccare l’opzione definitiva appena escono gli orari.", price: 0, bookingStatus: "da-prenotare" },
  { id: "d11-checkin", date: "2026-11-27", stopId: "zhangjiajie", startTime: "18:00", endTime: "20:00", name: "Cena e acquisti a Wulingyuan", category: "cibo", location: "Wulingyuan", notes: "Dopo il check-in, acquistare snack e acqua per il parco.", price: 25, bookingStatus: "non-serve" },
  { id: "d12-park", date: "2026-11-28", stopId: "zhangjiajie", startTime: "07:30", endTime: "17:30", name: "Zhangjiajie National Forest Park", category: "visita", location: "Wulingyuan Entrance", notes: "Itinerario Yuanjiajie + Tianzi Mountain; adattare a meteo e code.", price: 90, bookingStatus: "da-prenotare", sourceActivityId: "forest-park" },
  { id: "d13-fenghuang", date: "2026-11-29", stopId: "fenghuang", startTime: "09:00", endTime: "12:00", name: "Trasferimento a Fenghuang", category: "trasporto", location: "Zhangjiajie → Fenghuanggucheng", notes: "Treno veloce e Didi fino all’alloggio.", price: 0, bookingStatus: "da-prenotare" },
  { id: "d13-river", date: "2026-11-29", stopId: "fenghuang", startTime: "15:00", endTime: "20:30", name: "Città antica e Tuojiang illuminato", category: "visita", location: "Fenghuang Ancient Town", notes: "Barca prima del tramonto; passeggiata serale.", price: 15, bookingStatus: "non-serve", sourceActivityId: "tuojiang" },
  { id: "d14-wuzhen", date: "2026-11-30", stopId: "wuzhen", startTime: "07:00", endTime: "16:00", name: "Fenghuang → Wuzhen", category: "trasporto", location: "Via Changsha / Tongxiang", notes: "Seconda tratta critica; lasciare margine tra i cambi.", price: 0, bookingStatus: "da-prenotare" },
  { id: "d14-xizha", date: "2026-11-30", stopId: "wuzhen", startTime: "17:30", endTime: "20:30", name: "Xizha di sera", category: "visita", location: "Xizha Scenic Area", notes: "Dormire dentro o vicino all’area scenica.", price: 40, bookingStatus: "da-prenotare", sourceActivityId: "xizha" },
  { id: "d15-suzhou", date: "2026-12-01", stopId: "suzhou", startTime: "09:00", endTime: "11:00", name: "Transfer Wuzhen → Suzhou", category: "trasporto", location: "Hotel → Suzhou", notes: "Didi o transfer prenotato.", price: 0, bookingStatus: "da-prenotare" },
  { id: "d15-gardens", date: "2026-12-01", stopId: "suzhou", startTime: "12:00", endTime: "17:00", name: "Giardini classici e Pingjiang Road", category: "visita", location: "Humble Administrator’s Garden", notes: "Giardino prima, canali e cena dopo.", price: 20, bookingStatus: "da-prenotare", sourceActivityId: "humble-garden" },
  { id: "d16-shanghai", date: "2026-12-02", stopId: "shanghai", startTime: "09:00", endTime: "11:30", name: "Treno Suzhou → Shanghai", category: "trasporto", location: "Suzhou → Shanghai", notes: "Preferire Hongqiao se comodo per l’hotel.", price: 0, bookingStatus: "da-prenotare" },
  { id: "d16-bund", date: "2026-12-02", stopId: "shanghai", startTime: "14:00", endTime: "20:00", name: "Concessione Francese e Bund", category: "visita", location: "Xintiandi → Bund", notes: "Arrivare sul Bund poco prima dell’accensione delle luci.", price: 20, bookingStatus: "non-serve" },
  { id: "d17-shanghai", date: "2026-12-03", stopId: "shanghai", startTime: "09:30", endTime: "13:00", name: "Yu Garden e Old City", category: "visita", location: "Yuyuan", notes: "Ultimi acquisti senza allontanarsi troppo.", price: 20, bookingStatus: "da-prenotare" },
  { id: "d17-tower", date: "2026-12-03", stopId: "shanghai", startTime: "16:00", endTime: "19:00", name: "Shanghai Tower e ultima cena", category: "visita", location: "Lujiazui", notes: "Scegliere fascia tramonto; preparare i bagagli prima di uscire.", price: 45, bookingStatus: "da-prenotare", sourceActivityId: "tower" },
];

export const defaultChecklist = [
  "Confermare ritmo e tappe insieme",
  "Prenotare hotel cancellabili",
  "Risolvere Kunming → Zhangjiajie",
  "Risolvere Fenghuang → Wuzhen",
  "Prenotare ingressi di Pechino",
  "Verificare visto / ingresso in Cina",
  "Preparare eSIM, VPN e mappe offline",
  "Confermare assicurazione viaggio",
];

/**
 * Blocchi "treno/volo tra città" dell'agenda iniziale: ora le tratte hanno orari propri e
 * compaiono da sole nel giorno giusto, quindi questi doppioni vengono assorbiti nelle tratte.
 */
export const DEFAULT_TRANSFER_ITEMS: Record<string, [string, string]> = {
  "d04-train": ["beijing", "xian"],
  "d06-train": ["xian", "chengdu"],
  "d08-flight": ["chengdu", "kunming"],
  "d11-transfer": ["kunming", "zhangjiajie"],
  "d13-fenghuang": ["zhangjiajie", "fenghuang"],
  "d14-wuzhen": ["fenghuang", "wuzhen"],
  "d15-suzhou": ["wuzhen", "suzhou"],
  "d16-shanghai": ["suzhou", "shanghai"],
};

